In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.array(5,5,2)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.full(5,5)

array([5, 5, 5, 5, 5])

In [10]:
np.full(5,3,9)

TypeError: Cannot interpret '9' as a data type

In [11]:
np.full(5,4)

array([4, 4, 4, 4, 4])

In [12]:
np.full((5,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [13]:
np.full((5,5,2),99, dtype=float)

array([[[99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.]],

       [[99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.]],

       [[99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.]],

       [[99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.]],

       [[99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.],
        [99., 99.]]])

In [14]:
np.random.rand(5)

array([0.09859221, 0.79213146, 0.51809764, 0.92520051, 0.00311296])

In [15]:
np.random.randint(9)

1

In [16]:
np.random.randint(5,6)

5

In [17]:
np.arange(5,4)

array([], dtype=int64)

In [18]:
np.arange(2,9,5)

array([2, 7])

In [19]:
np.arange(0,99,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [20]:
np.linespace(0,1,5)

AttributeError: module 'numpy' has no attribute 'linespace'

In [21]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [23]:
np.array([1,2,3,4,5], dtype='int8')

array([1, 2, 3, 4, 5], dtype=int8)

In [24]:
a.dtype

dtype('int64')

In [25]:
a.shape

(5,)

In [29]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
a.ndim

2

In [31]:
a.size

25

In [32]:
a.nbytes

200

In [33]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,0])


In [34]:
z = np.array(x,y)

TypeError: Cannot construct a dtype from an array

In [35]:
a = np.array([[5,4,3,6],[2,1,3,4]])

In [36]:
a

array([[5, 4, 3, 6],
       [2, 1, 3, 4]])

In [37]:
np.arange(9999)

array([   0,    1,    2, ..., 9996, 9997, 9998])

In [38]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [39]:
a

array([[5, 4, 3, 6],
       [2, 1, 3, 4]])

In [40]:
a**2

array([[25, 16,  9, 36],
       [ 4,  1,  9, 16]])

In [41]:
a/4

array([[1.25, 1.  , 0.75, 1.5 ],
       [0.5 , 0.25, 0.75, 1.  ]])

In [42]:
a*2

array([[10,  8,  6, 12],
       [ 4,  2,  6,  8]])

In [43]:
a+5

array([[10,  9,  8, 11],
       [ 7,  6,  8,  9]])

In [44]:
b

NameError: name 'b' is not defined

In [45]:
x

array([1, 2, 3, 4, 5])

In [46]:
a @ b

NameError: name 'b' is not defined

In [47]:
a@x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [48]:
a.dot(x)

ValueError: shapes (2,4) and (5,) not aligned: 4 (dim 1) != 5 (dim 0)