In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [3]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [4]:
%ls

day1.ipynb  day2.ipynb


In [5]:
%time for i in range(1000): i

CPU times: user 191 µs, sys: 45 µs, total: 236 µs
Wall time: 247 µs


In [6]:
arr*arr

array([[ 1,  4,  9, 16, 25],
       [36, 49, 64, 81,  0]])

In [7]:
arr/arr

/tmp/ipykernel_4302/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., nan]])

In [8]:
arr+arr

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18,  0]])

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr.ndim

2

In [11]:
arr.nbytes

80

In [12]:
arr.shape

(2, 5)

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [14]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr2 = np.empty((4,5))

In [16]:
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
arr[(1,2)]

8

In [19]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [20]:
arr[(1, 4)]

0

In [22]:
arr[(::-3)]

SyntaxError: invalid syntax (1620967351.py, line 1)

In [23]:
arr.sum()

45

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [25]:
arr.sum(axis=1)

array([15, 30])

In [26]:
arr.sum(axis=0)

array([ 7,  9, 11, 13,  5])

In [27]:
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
arr2 = np.array([[1,2], [3,4],[5,6]])

In [29]:
arr3

NameError: name 'arr3' is not defined

In [30]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
arr.dot(arr2.transpose())

ValueError: shapes (2,5) and (2,3) not aligned: 5 (dim 1) != 2 (dim 0)

In [32]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [33]:
len(dir(np))

599

In [34]:
arr.cross(arr2)

AttributeError: 'numpy.ndarray' object has no attribute 'cross'

In [35]:
np.cross(arr, arr2)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [36]:
np.sort(arr)

array([[1, 2, 3, 4, 5],
       [0, 6, 7, 8, 9]])

In [37]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [38]:
np.sort(arr,axis=0)

array([[1, 2, 3, 4, 0],
       [6, 7, 8, 9, 5]])

In [40]:
a = np.full(2, 5)

In [41]:
a 

array([5, 5])

In [42]:
a = np.full((5,5), 6)

In [43]:
a

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [44]:
b = np.full((5,5), 9)

In [47]:
a+b

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [48]:
c = a+b

In [49]:
c

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [50]:
np.argsort(arr)

array([[0, 1, 2, 3, 4],
       [4, 0, 1, 2, 3]])

In [51]:
np.argmin(arr)

9

In [52]:
np.argmax(arr) # give us index

8

In [53]:
a*b

array([[54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54]])

In [54]:
d = a*b

In [55]:
%time d

CPU times: user 7 µs, sys: 1 µs, total: 8 µs
Wall time: 13.4 µs


array([[54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54]])