In [1]:
import numpy as np

In [2]:
a = np.arange(5)

In [3]:
a

array([0, 1, 2, 3, 4])

In [4]:
b = np.array([2,234,34,534,56,7,34,5,3,234,456,567,4563,453,452,32,3,233])
b.shape

(18,)

In [5]:
b = b.reshape(3,6) # row, column

In [6]:
b

array([[   2,  234,   34,  534,   56,    7],
       [  34,    5,    3,  234,  456,  567],
       [4563,  453,  452,   32,    3,  233]])

In [7]:
b.reshape(6,3) # row , column

array([[   2,  234,   34],
       [ 534,   56,    7],
       [  34,    5,    3],
       [ 234,  456,  567],
       [4563,  453,  452],
       [  32,    3,  233]])

In [8]:
b = b.reshape(1,18)

In [9]:
b

array([[   2,  234,   34,  534,   56,    7,   34,    5,    3,  234,  456,
         567, 4563,  453,  452,   32,    3,  233]])

In [10]:
np.argsort(b) #this is return the index

array([[ 0, 16,  8,  7,  5, 15,  6,  2,  4, 17,  1,  9, 14, 13, 10,  3,
        11, 12]])

In [11]:
np.argmin(b) # return the index

0

In [12]:
np.argmax(b)# return the index

12

In [13]:
np.argwhere(b)

array([[ 0,  0],
       [ 0,  1],
       [ 0,  2],
       [ 0,  3],
       [ 0,  4],
       [ 0,  5],
       [ 0,  6],
       [ 0,  7],
       [ 0,  8],
       [ 0,  9],
       [ 0, 10],
       [ 0, 11],
       [ 0, 12],
       [ 0, 13],
       [ 0, 14],
       [ 0, 15],
       [ 0, 16],
       [ 0, 17]])

In [14]:
np.argpartition(b, 1)

array([[ 0,  8,  2,  3,  4,  5,  6,  7,  1,  9, 10, 11, 12, 13, 14, 15,
        16, 17]])

In [15]:
np.arange(9999999)

array([      0,       1,       2, ..., 9999996, 9999997, 9999998])